= Gaze Controlled Computer
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title: Table of Contents

toc::[]

== Abstract
Our gaze controlled computer software will be implemented in Python with the help of OpenCV and PyAutoGUI. A 1080p webcam mounted on an adjustable arm that will be anchored to a table will be used as inputs to our software. This camera will gather frame data of the user’s eyes, passing each frame through image filters, edge detection and circular Hough transform. These processed frames can then be utilized to calibrate and track the user’s eye movements. The data will then be mapped to the screen and the user can interact with the computer by blinking. A virtual keyboard can be brought up to assist the user with typing. The keyboard will be controlled by looking at a key for a certain amount of time. This software will enable physically disabled people to operate computers.

== Prerequisites

Recommended to be used with Pycharm: https://www.jetbrains.com/pycharm/

Within Pycharm click on requirements.txt and install requirements

Download and unpack the trained model file from http://dlib.net/files.  shape_predictor_68_face_landmarks.dat.bz2.
The file should be placed in the /models.







